html_translator = {
    "<b>Today:": "<b>Heute:",
    ">Person1<": ">{person1}<",
    ">Person2<": ">{person2}<",
    ">Tracker<": ">Tracker<",
    ">Foods<": ">Essen<",
    ">Weight<": ">Gewicht<",
    ">Settings<": ">Einstellungen<",
    ">Daily Nutrition Tracker<": ">Täglicher Nährwert Tracker<",
    ">Remaining For Today:<": ">Übrig für Heute:<",
    ">Calories": ">Kalorien",
    ">Amount": ">Menge",
    ">Food Name:<": ">Name Essen:<",
    ">Enter either a value or a food!<": ">Entweder ein Essen oder einen Wert eingeben!<",
    ">Date": ">Datum",
    "Yesterday": "Gestern",
    ">Today<": ">Heute<",
    "value=\"Today\"": "value=\"Heute\"",
    "Tomorrow": "Morgen",
    ">Add<": "Einfügen",
    ">Undo<": ">Rückgängig<",
    "Tracked Values": "Getrackte Werte",
    ">Type": ">Typ",
    ">Add Foods and Receipes<": ">Füge Essen und Rezepte hinzu<",
    ">Add new food item by inserting the protein and calories per 100g.<":
    ">Füge ein Essen mit der Menge an Protein und Kalorien pro 100g hinzu.<",
    ">Name already exists!<": ">Name bereits vergeben!<",
    ">Add Food<": "Essen hinzufügen",
    ">Create a new receipe with different foods.<":
    ">Erstelle ein Rezept mit verschiedenen Essen.<",
    ">Add to Receipe<": ">Zum Rezept hinzufügen<",
    ">Food<": ">Essen<",
    ">Receipe Name:<": ">Name Rezept:<",
    ">Container:<": ">Behälter:<",
    ">Total weight:<": ">Gesamtgewicht:<",
    ">Save receipe<": ">Rezept speichern<",
    ">Remove Food<": ">Essen entfernen<",
    ">Weight Tracking<": ">Gewicht tracken<",
    ">Weight loss since start: <": ">Gewichtsverlust seit Start: <",
    ">Weight:<": ">Gewicht:<",
    ">Invalid date!<": ">Ungültiges Datum!<",
    ">Add Weight<": ">Gewicht hinzufügen<",
    "Weight Values": "Gewichtswerte",
    ">Enter daily amount of protein and calories.<":
    ">Täglichen Bedarf and Protein und Kalorien angeben.<",
    ">Change Daily Settings<": ">Tägliche Einstellung ändern<",
    ">Settings saved!<": ">Einstellung gespeichert!<",
    ">Save Data to File<": ">Datei in Datei speichern<",
    ">Load Data from File<": ">Daten von Datei laden<",
    "Command Execution History": "Vergangene ausgeführte Befehle",
    ">Last 20 commands<": ">Letzten 20 Befehle<",
},

app_translator = {
    "Pan (small)": "Pfanne (klein)",
    "Pan (mid)": "Pfanne (mittel)",
    "Pan (big)": "Pfanne (groß)",
    "Pan (deep)": "Pfanne (tief)",
    "Pot (small)": "Topf (klein)",
    "Pot (mid)": "Topf (mittel)",
    "Pot (big)": "Topf (groß)",
    "Pot old (sauce)": "Topf alt (Soße)",
    "Pot old (small)": "Topf alt (klein)",
    "Pot old (mid)": "Topf alt (mittel)",
    "Pot old (big)": "Topf alt (groß)",
    "Pot old (deep)": "Topf alt (tief)",
    "Backing Pan (small)": "Backform (klein)",
    "Backing Pan (big)": "Backform (groß)",
    "Backing Pan (silicone)": "Backform (Silikon)",
    "Rice Cooker": "Reiskocher",
    "Mixer Ninja (small)": "Mixer Ninja (klein)",
    "Mixer Ninja (mid)": "Mixer Ninja (mittel)",
    "Mixer Ninja (big)": "Mixer Ninja (groß)",
    "Le Creuset (Pan)": "Le Creuset (Pfanne)",
    "Le Creuset (Pot)": "Le Creuset (Topf)",
    "Le Creuset (Roaster)": "Le Creuset (Bräter)",
    "Backing Tray": "Backblech",
    "Plastic Bowl (small)": "Plastikschüssel (klein)",
    "Plastic Bowl (mid)": "Plastikschüssel (mittel)",
    "Plastic Bowl (big)": "Plastikschüssel (groß)",
    "Plastic Bowl (very big)": "Plastikschüssel (sehr groß)",
    "Plastic Bowl (blue)": "Plastikschüssel (blau)",
    "Tin Bowl (small)": "Blechschüssel (klein)",
    "Tin Bowl (big)": "Blechschüssel (groß)",
    ">Today:": ">Heute:",
    "Direct value input": "Direkter Eingabewert",
    "Enter a name and amount!": "Name und Menge angeben!",
    "Food name not found!": "Essensname nicht gefunden!",
    "Enter either a value or a food!": "Entweder Wert oder Essen eingeben!",
    "Tracker: added value for ": "Tracker: Wert hinzugefügt für ",
    ", Calories:": ", Kalorien:",
    ", Type:": ", Typ:",
    "Tracker: removed value from ": "Tracker: Wert entfernt von ",
    "Remaining For ": "Übrig für ",
    "No Name given!": "Keine Name gegeben!",
}
